[package]
name = "bpexcel2_pdf"
version = "1.1.2"
description = "Bonne Pioche Excel to Pdf"
authors = [ "dev@akylasfr" ]
license = "MIT"
repository = "https://github.com/Akylas/pbexcel2pdf"
default-run = "bpexcel2_pdf"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
flate2 = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "2", features = [] }
tauri-plugin-window-state = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
tauri-plugin-process = "2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "z"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
